image: "nexus.bz-openlab.ru:10443/huawei/koala-ci:0.2"

stages:
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.setup:
    script:
        - npm config set registry https://repo.huaweicloud.com/repository/npm/
        - npm config set @ohos:registry https://repo.harmonyos.com/npm/
        - npm config set @koalaui:registry https://nexus.bz-openlab.ru:10443/repository/koala-npm/
        - npm config set @panda:registry https://nexus.bz-openlab.ru:10443/repository/koala-npm/
        - npm config set //nexus.bz-openlab.ru:10443/repository/koala-npm/:_auth $NEXUS_NPM_PASS
        - npm i --no-audit --no-fund
        - npm i --prefix external --no-audit --no-fund

idlize sanity:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.setup, script]
  script:
    - npm run sanity

pg java:run:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.setup, script]
  script:
    - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64 npm run run:java

run arkts subset:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.setup, script]
    - PANDA_SDK_VERSION=1.5.0-dev.7123 npm run panda:sdk:install
  script:
    - npm run compile:all:arkts:idl
    - ls ./external/incremental/compat/build/abc/arkts/index.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkArkui-external.idlInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkBlank.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkBlankInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkBottomTabBarStyleBuilder.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkButton.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkButtonInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkCalendarPicker.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkCalendarPickerInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkCanvas.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkCanvasGradientMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkCanvasInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkCanvasPathMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkCanvasPatternMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkCanvasRendererMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkCanvasRenderingContext2DMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkClassWithConstructorAndAllOptionalParamsDTSMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkClassWithConstructorAndFieldsAndMethodsDTSMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkClassWithConstructorAndMethodsDTSMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkClassWithConstructorAndNonOptionalParamsDTSMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkClassWithConstructorAndSomeOptionalParamsDTSMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkClassWithConstructorAndStaticMethodsDTSMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkClassWithConstructorAndWithoutParamsDTSMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkColumn.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkColumnInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkCommon.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkCommonInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkDotIndicatorBuilder.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkDrawingRenderingContextMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkEmbeddedComponent.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkEmbeddedComponentInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkEnumsInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkEventTargetInfoMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkFormComponent.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkFormComponentInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkGestureInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkGestureModifierMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkGestureRecognizerMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkGridContainer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkGridContainerInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkICurveMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkImage.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkImageBitmapMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkImageInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkIndicatorBuilder.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkInterop-types.idlInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkList.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkListInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkMatrix2DMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkMatrix2dInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkNavDestination.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkNavDestinationContextMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkNavDestinationInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkNavPathStackMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkNavigation.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkNavigationInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkNavigationTransitionProxyMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkParticleInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkRect.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkRectInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkResourceInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkScroll.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkScrollInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkScrollerMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkSecurityComponentInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkSelect.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkSelectInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkShape.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkShapeInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkSidebar.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkSidebarInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkSliderInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkSpanInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkStdlib.idlInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkStyledStringInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkStyledStringMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkSubTabBarStyleBuilder.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkSwiper.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkSwiperControllerMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkSwiperInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkSymbolglyph.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkSymbolglyphInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkTabContent.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkTabContentInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkTabs.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkTabsInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkTest.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkTestInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkText.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkTextControllerMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkTextInput.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkTextInputInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkTextInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkTextPicker.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkTextPickerDialogMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkTextPickerInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkUIExtensionProxyMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkUiExtensionComponent.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkUiExtensionComponentInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkUnitsInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkVector.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkVectorInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkWeb.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkWebInterfaces.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkWebResourceResponseMaterialized.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ArkoalaControl.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/CallbackRegistry.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ComponentBase.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/ConflictedDeclarations.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/Declarations.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/Events.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/Finalizable.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/MaterializedBase.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/NativePeerNode.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/PeerNode.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/SyntheticDeclarations.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/common.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/index.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/main.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peer_events.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/test_utils.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/arkts/NativeModule.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/arkts/index.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/arkts/type_check.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkBlankPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkButtonPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkCalendarPickerPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkCanvasPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkColumnPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkCommonPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkEmbeddedComponentPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkFormComponentPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkGridContainerPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkImagePeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkListPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkNavDestinationPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkNavigationPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkRectPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkScrollPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkSelectPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkShapePeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkSidebarPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkSwiperPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkSymbolglyphPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkTabContentPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkTabsPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkTestPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkTextInputPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkTextPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkTextPickerPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkUINodeType.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkUiExtensionComponentPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkVectorPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/ArkWebPeer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/CallbackKind.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/Serializer.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/peers/SerializerBase.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/shared/ArkResource.abc
    - ls out/abc-subset/sig/arkoala-arkts/arkui/src/generated/shared/generated-utils.abc
    - ls external/interop/build/abc/src/arkts/buffer.abc
    - ls external/interop/build/abc/src/arkts/callback.abc
    - ls external/interop/build/abc/src/arkts/index.abc
    - ls external/interop/build/abc/src/arkts/types.abc
    - ls external/interop/build/abc/src/interop/ResourceManager.abc
    - ls external/incremental/runtime/build/abc/src/index.abc
    - ls external/incremental/runtime/build/abc/src/internals.abc
    - ls external/incremental/runtime/build/abc/src/animation/AnimatedState.abc
    - ls external/incremental/runtime/build/abc/src/animation/AnimationRange.abc
    - ls external/incremental/runtime/build/abc/src/animation/Easing.abc
    - ls external/incremental/runtime/build/abc/src/animation/EasingSupport.abc
    - ls external/incremental/runtime/build/abc/src/animation/GlobalTimer.abc
    - ls external/incremental/runtime/build/abc/src/animation/TimeAnimation.abc
    - ls external/incremental/runtime/build/abc/src/animation/memo.abc
    - ls external/incremental/runtime/build/abc/src/memo/bind.abc
    - ls external/incremental/runtime/build/abc/src/memo/changeListener.abc
    - ls external/incremental/runtime/build/abc/src/memo/contextLocal.abc
    - ls external/incremental/runtime/build/abc/src/memo/entry.abc
    - ls external/incremental/runtime/build/abc/src/memo/node.abc
    - ls external/incremental/runtime/build/abc/src/memo/remember.abc
    - ls external/incremental/runtime/build/abc/src/memo/repeat.abc
    - ls external/incremental/runtime/build/abc/src/memo/testing.abc
    - ls external/incremental/runtime/build/abc/src/states/Dependency.abc
    - ls external/incremental/runtime/build/abc/src/states/Disposable.abc
    - ls external/incremental/runtime/build/abc/src/states/GlobalStateManager.abc
    - ls external/incremental/runtime/build/abc/src/states/Journal.abc
    - ls external/incremental/runtime/build/abc/src/states/Observable.abc
    - ls external/incremental/runtime/build/abc/src/states/State.abc
    - ls external/incremental/runtime/build/abc/src/tree/IncrementalNode.abc
    - ls external/incremental/runtime/build/abc/src/tree/PrimeNumbers.abc
    - ls external/incremental/runtime/build/abc/src/tree/ReadonlyTreeNode.abc
    - ls external/incremental/runtime/build/abc/src/tree/TreeNode.abc
    - ls external/incremental/runtime/build/abc/src/tree/TreePath.abc
    - ls external/incremental/runtime/build/abc/src/tree/TreeUpdater.abc
    - ls external/incremental/compat/build/abc/index.abc
    - ls external/incremental/compat/build/abc/arkts/array.abc
    - ls external/incremental/compat/build/abc/arkts/atomic.abc
    - ls external/incremental/compat/build/abc/arkts/double.abc
    - ls external/incremental/compat/build/abc/arkts/finalization.abc
    - ls external/incremental/compat/build/abc/arkts/index.abc
    - ls external/incremental/compat/build/abc/arkts/performance.abc
    - ls external/incremental/compat/build/abc/arkts/prop-deep-copy.abc
    - ls external/incremental/compat/build/abc/arkts/reflection.abc
    - ls external/incremental/compat/build/abc/arkts/strings.abc
    - ls external/incremental/compat/build/abc/arkts/ts-reflection.abc
    - ls external/incremental/compat/build/abc/arkts/types.abc
    - ls external/incremental/common/build/abc/src/Errors.abc
    - ls external/incremental/common/build/abc/src/Events.abc
    - ls external/incremental/common/build/abc/src/Finalization.abc
    - ls external/incremental/common/build/abc/src/KoalaProfiler.abc
    - ls external/incremental/common/build/abc/src/MarkableQueue.abc
    - ls external/incremental/common/build/abc/src/Matrix33.abc
    - ls external/incremental/common/build/abc/src/Matrix44.abc
    - ls external/incremental/common/build/abc/src/PerfProbe.abc
    - ls external/incremental/common/build/abc/src/Point.abc
    - ls external/incremental/common/build/abc/src/Point3.abc
    - ls external/incremental/common/build/abc/src/index.abc
    - ls external/incremental/common/build/abc/src/koalaKey.abc
    - ls external/incremental/common/build/abc/src/math.abc
    - ls external/incremental/common/build/abc/src/sha1.abc
    - ls external/incremental/common/build/abc/src/stringUtils.abc
    - ls external/incremental/common/build/abc/src/uniqueId.abc 
    - ls ./out/abc-subset/sig/arkoala-arkts/arkui/src/generated/main.abc

# arkts subset tsc:
#   stage: test
#   tags:
#     - idlize-ci
#     - koala-ci
#   before_script:
#     - !reference [.setup, script]
#   script:
#     - npm run check:arkts:subset:tsc

build native-arm64:
  stage: test
  allow_failure: true
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.setup, script]
  script:
    - KOALA_BZ=1 OPENLAB_USERNAME=koala-ci OPENLAB_PASSWORD=w1llUgu3ss npm run native:ts:arm64

build native-arm32:
  stage: test
  allow_failure: true
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.setup, script]
  script:
    - KOALA_BZ=1 OPENLAB_USERNAME=koala-ci OPENLAB_PASSWORD=w1llUgu3ss npm run native:ts:arm32

build arkoala.har:
  stage: test
  allow_failure: true
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.setup, script]
  script:
    - KOALA_BZ=1 OPENLAB_USERNAME=koala-ci OPENLAB_PASSWORD=w1llUgu3ss npm run arkoala:har-arm32
    - cp $CI_PROJECT_DIR/external/arkoala/har/app/arkoala/build/default/outputs/default/arkoala.har $CI_PROJECT_DIR/
  artifacts:
      expire_in: 1 week
      paths:
          - arkoala.har

publish idlize:
    stage: test
    tags:
      - idlize-ci
      - koala-ci
    rules:
      - if: $CI_PIPELINE_SOURCE == "schedule"
        when: never
      - if: $CI_COMMIT_BRANCH == "master"
        when: on_success
    before_script:
      - !reference [.setup, script]
    script:
        - cd $CI_PROJECT_DIR
        - sed -i "s/+devel/-dev.$CI_PIPELINE_IID/" package.json
        - KOALA_BZ=1 npm run upload

