package api.internal.component.ets;
import arkui.component.units.Length as Length;
import arkui.component.units.Padding as Padding;
import arkui.component.units.LocalizedPadding as LocalizedPadding;
import arkui.component.units.ResourceStr as ResourceStr;
import arkui.component.units.BorderOptions as BorderOptions;
import arkui.component.units.LocalizedEdgeWidths as LocalizedEdgeWidths;
import arkui.component.units.EdgeWidths as EdgeWidths;
import arkui.component.units.EdgeColors as EdgeColors;
import arkui.component.units.LocalizedEdgeColors as LocalizedEdgeColors;
import arkui.component.units.EdgeStyles as EdgeStyles;
import arkui.component.units.BorderRadiuses as BorderRadiuses;
import arkui.component.units.LocalizedBorderRadiuses as LocalizedBorderRadiuses;
import arkui.component.units.ResourceColor as ResourceColor;
import arkui.component.common.LayoutPolicy as LayoutPolicy;
import arkui.component.enums.BorderStyle as BorderStyle;

callback TextFieldValueCallback = void (ResourceStr value);
[Entity=Class]
interface TextFieldOps {
    static pointer registerTextFieldValueCallback(pointer node, ResourceStr value, TextFieldValueCallback callback);
    static pointer textFieldOpsSetWidth(pointer node, optional (Length or LayoutPolicy) value);
    static pointer textFieldOpsSetHeight(pointer node, optional (Length or LayoutPolicy) value);
    static pointer textFieldOpsSetPadding(pointer node, optional (Padding or Length or LocalizedPadding) value);
    static pointer textFieldOpsSetMargin(pointer node, optional (Padding or Length or LocalizedPadding) value);
    static pointer textFieldOpsSetBorder(pointer node, optional BorderOptions value);
    static pointer textFieldOpsSetBorderWidth(pointer node, optional (Length or EdgeWidths or LocalizedEdgeWidths) value);
    static pointer textFieldOpsSetBorderColor(pointer node, optional (ResourceColor or EdgeColors or LocalizedEdgeColors) value);
    static pointer textFieldOpsSetBorderStyle(pointer node, optional (BorderStyle or EdgeStyles) value);
    static pointer textFieldOpsSetBorderRadius(pointer node, optional (Length or BorderRadiuses or LocalizedBorderRadiuses) value);
    static pointer textFieldOpsSetBackgroundColor(pointer node, optional ResourceColor value);
};
