package idlize.internal;

// interface Finalizable {};
// interface RefCounted {};
interface SerializerBase {};
interface DeserializerBase {};
interface deserializeAndCallCallback {};
interface checkArkoalaCallbacks {};
interface CallbackTransformer {};
interface CallbackBuffer {};
interface CallbackResourceHolder {};
interface Tag {};
interface CallbackKind {};
interface KVMContext {};
interface TypeChecker {};
interface TSTypeChecker {};
