package "org.openharmony.idl";

[GlobalScope, NativeModule, NoBridge]
interface Test {
    KInt TestCallIntNoArgs(KInt arg0);
    KInt TestCallIntIntArraySum(KInt arg0, KInt32ArrayPtr arg1, KInt arg2);
    void TestCallVoidIntArrayPrefixSum(KInt arg0, KInt32ArrayPtr arr, KInt arg2);
    KInt TestCallIntRecursiveCallback(KInt arg0, KUint8ArrayPtr arr, KInt arg2);
    KInt TestCallIntMemory(KInt arg0, KInt arg1);
};
