#!/bin/bash

# Copyright (c) 2022-2023 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SCRIPT_DIR=`dirname "${BASH_SOURCE[0]}"`

. $SCRIPT_DIR/common

EXCLUDE_PANDA_FILE=$DTS_INTERFACES_FILE:$EXCLUDE_PANDA_FILE
PANDA_LIB_FILES=$(echo $(find $PANDA_LIB_PATH -not -name $(echo $EXCLUDE_PANDA_FILE | sed 's/:/ -not -name /g') -name *.abc -exec echo {}: \;) | tr -d ' ')
# Set $DTS_INTERFACES_FILE to first position. This is a workaround for the issue: https://rnd-gitlab-msc.huawei.com/rus-os-team/virtual-machines-and-tools/panda/-/issues/18012
PANDA_LIB_FILES=$PANDA_LIB_PATH/$DTS_INTERFACES_FILE:$PANDA_LIB_FILES
$PANDA_SDK/$ARCH_TOOLS/bin/ark --load-runtimes=ets --boot-panda-files $PANDA_SDK/ets/etsstdlib.abc:$PANDA_LIB_FILES $@ index.ETSGLOBAL::main

