package "org.openharmony.idlize.predefined";

interface Loader {
    i32 LoadVirtualMachine(i32 vmType, String arg1, String arg2);
    boolean RunApplication(i32 arg0, i32 arg1);
    pointer StartApplication(String appUrl, String appParams);
    void EmitEvent(i32 eventType, i32 target, i32 arg0, i32 arg1);
    i32 CallVirtualMachine(i32 vmType, sequence<u8> data, i32 inputLength, i32 maxOutputLength);
};
