package demo.test.simple;

namespace structs {
    interface Point {
        attribute i32 x;
        attribute i32 y;
    };

    interface Star {
        attribute String name;
        attribute Point location;
    };

    interface StarMap {
        attribute sequence<Star> data;
    };

    interface StarMapController {
        void add(Star star);
        i32 sum();
        void addMap(StarMap map);
    };
};
