package ohos.web.webview;

[DefaultExport]
namespace webview {
    interface WebHeader {
        attribute String headerKey;
        attribute String headerValue;
    };
    [Entity=Class]
    interface WebviewController {
        constructor();
        static void initializeWebEngine();
        void loadUrl((String or Resource) url, optional sequence<WebHeader> headers);
    };
};