package ohos.web.webview;

[DefaultExport]
namespace webview {
    interface WebHeader {
        attribute String headerKey;
        attribute String headerValue;
    };

    [Entity=Class]
    interface WebviewController {
        void loadUrl(optional sequence<WebHeader> headers);
    };
};