package org.openharmony.idlize.predefined;

[TSType=RuntimeType, JavaType=RuntimeType, CJType=RuntimeType, CPPType=RuntimeType]
interface RuntimeType {};
[TSType=Materialized, JavaType=Materialized, CJType=Materialized, CPPType=Materialized]
interface Materialized {};
[TSType=CallbackResource, JavaType=CallbackResource, CJType=CallbackResource, CPPType=CallbackResource]
interface CallbackResource {};
[CPPType=VMContext]
interface VMContext {};
