package org.openharmony.idlize.predefined;

[TSType=RuntimeType, CPPType=RuntimeType, Predefined]
interface RuntimeType {};
[TSType=Materialized, CPPType=Materialized, Predefined]
interface Materialized {};
[TSType=CallbackResource, CPPType=CallbackResource, Predefined]
interface CallbackResource {};
[CPPType=VMContext]
interface VMContext {};
