[Entity=Interface]
interface ContentModifierInternal {
    attribute i64 contentModifierObjId;
};

[Entity=Interface, TypeParameters="T"]
interface CommonConfiguration {
    attribute boolean enabled;
    attribute ContentModifierInternal contentModifier;
};

[Synthetic]
callback CheckBoxContentBuilder = pointer (pointer parentNode, CheckBoxConfiguration config);

[Entity=Interface]
interface CheckBoxContentModifier : ContentModifierInternal {
    attribute CheckBoxContentBuilder builder;
};
