callback RestrictedWorker_onexit_Callback = void (number code);
callback RestrictedWorker_onerror_Callback = void (ErrorEvent ev);
callback RestrictedWorker_onmessage_Callback = void (MessageEvents event);

[Entity=Class]
interface RestrictedWorker {
    constructor(String scriptURL, optional WorkerOptions options);
    [Optional] attribute RestrictedWorker_onexit_Callback onexit;
    [Optional] attribute RestrictedWorker_onerror_Callback onerror;
    [Optional] attribute RestrictedWorker_onmessage_Callback onmessage;
    [Optional] attribute RestrictedWorker_onmessage_Callback onmessageerror;
    [Throws] void postMessage(Object message, sequence<buffer> transfer);
    [Throws] void postMessage(Object message, optional PostMessageOptions options);
    [Throws] void postMessageWithSharedSendable(Object message, optional sequence<buffer> transfer);
    [Throws] void on(String Type, WorkerEventListener listener);
    [Throws] void once(String Type, WorkerEventListener listener);
    [Throws] void off(String Type, optional WorkerEventListener listener);
    [Throws] void terminate();
    [Throws] void addEventListener(String Type, WorkerEventListener listener);
    [Throws] boolean dispatchEvent(Event event);
    [Throws] void removeEventListener(String Type, optional WorkerEventListener callback_);
    [Throws] void removeAllListener();
    [Throws] void registerGlobalCallObject(String instanceName, Object globalCallObject);
    [Throws] void unregisterGlobalCallObject(optional String instanceName);
};
