[Entity=Interface]
interface WebHeader {
    attribute String headerKey;
    attribute String headerValue;
};

[Entity=Class]
interface WebviewController {
  static void initializeWebEngine();
  void loadUrl((String or Resource) url, optional sequence<WebHeader> headers);
};
