import { Finalizable } from "../peers/Finalizable"
import { NativePeerNode } from "../peers/PeerNode"
import { nativeModule } from "@koalaui/arkoala"
import { isPixelMap, isResource, isInstanceOf, runtimeType, RuntimeType}  from "../type_utils"
import { createSerializer, Serializer } from "../peers/Serializer"
import { withLength, withLengthArray, registerCallback, SerializerBase } from "../peers/SerializerBase"
import { unsafeCast } from "../generated-utils"