build interfaces:
  stage: build
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.npm, script]
  script:
    - npm run -C interfaces compile
  needs:
    - download sdk
  artifacts:
    paths:
      - interfaces/dist

check arkui interfaces:
  allow_failure: true
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  needs:
    - download sdk
    - build external
  script:
    - !reference [.npm, script]
    - npm run compile --prefix core
    - npm run compile --prefix idlinter
    - npm run run:sdk --prefix etsgen
    - node idlinter --check interfaces/interfaces etsgen/out
