interface AstNode {};
interface Context {};

dictionary ScriptFunctionFlags {
};
dictionary ModifierFlags {
};
dictionary Es2pandaScriptFunctionFlags {
};

interface BlockStatement : AstNode {
    constructor(Context context, sequence<AstNode> statementList, i32 statementListLen);

    void SetScope(Context context, AstNode ast, Scope scope);
    sequence<AstNode> StatementsConst(Context context, AstNode ast);
    sequence<AstNode> Statements(Context context, AstNode ast);
    void SetStatements(Context context, AstNode ast, sequence<AstNode> statementList, i32 statementListLen);
    void AddTrailingBlock(Context context, AstNode ast, AstNode stmt, AstNode trailingBlock);
};

interface ScriptFunction : AstNode {
    constructor(Context context, AstNode databody, FunctionSignature datasignature, int datafuncFlags, int dataflags);
    AstNode IdConst(Context context, AstNode ast);
    AstNode Id(Context context, AstNode ast);
    Signature SignatureConst(Context context, AstNode ast);
    Signature Signature(Context context, AstNode ast);
    FunctionSignature IrSignature(Context context, AstNode ast);
    sequence<AstNode> ParamsConst(Context context, AstNode ast);
    sequence<AstNode> Params(Context context, AstNode ast);
    size_t DefaultParamIndexConst(Context context, AstNode ast);
    sequence<AstNode> ReturnStatementsConst(Context context, AstNode ast);
    sequence<AstNode> ReturnStatements(Context context, AstNode ast);
    AstNode TypeParamsConst(Context context, AstNode ast);
    AstNode TypeParams(Context context, AstNode ast);
    AstNode BodyConst(Context context, AstNode ast);
    AstNode Body(Context context, AstNode ast);
    void AddReturnStatement(Context context, AstNode ast, AstNode returnStatement);
    void SetBody(Context context, AstNode ast, AstNode body);
    AstNode ReturnTypeAnnotationConst(Context context, AstNode ast);
    AstNode ReturnTypeAnnotation(Context context, AstNode ast);
    void SetReturnTypeAnnotation(Context context, AstNode ast, AstNode node);
    bool IsEntryPointConst(Context context, AstNode ast);
    bool IsGeneratorConst(Context context, AstNode ast);
    bool IsAsyncFuncConst(Context context, AstNode ast);
    bool IsAsyncImplFuncConst(Context context, AstNode ast);
    bool IsArrowConst(Context context, AstNode ast);
    bool IsOverloadConst(Context context, AstNode ast);
    bool IsExternalOverloadConst(Context context, AstNode ast);
    bool IsConstructorConst(Context context, AstNode ast);
    bool IsGetterConst(Context context, AstNode ast);
    bool IsSetterConst(Context context, AstNode ast);
    bool IsMethodConst(Context context, AstNode ast);
    bool IsProxyConst(Context context, AstNode ast);
    bool IsStaticBlockConst(Context context, AstNode ast);
    bool IsEnumConst(Context context, AstNode ast);
    bool IsHiddenConst(Context context, AstNode ast);
    bool IsExternalConst(Context context, AstNode ast);
    bool IsImplicitSuperCallNeededConst(Context context, AstNode ast);
    bool HasBodyConst(Context context, AstNode ast);
    bool HasRestParameterConst(Context context, AstNode ast);
    bool HasReturnStatementConst(Context context, AstNode ast);
    bool HasThrowStatementConst(Context context, AstNode ast);
    bool IsThrowingConst(Context context, AstNode ast);
    bool IsRethrowingConst(Context context, AstNode ast);
    bool IsDynamicConst(Context context, AstNode ast);
    bool IsExtensionMethodConst(Context context, AstNode ast);
    Es2pandaScriptFunctionFlags FlagsConst(Context context, AstNode ast);
    void SetIdent(Context context, AstNode ast, AstNode id);
    void SetSignature(Context context, AstNode ast, Signature signature);
    void AddFlag(Context context, AstNode ast, Es2pandaScriptFunctionFlags flags);
    void AddModifier(Context context, AstNode ast, Es2pandaModifierFlags flags);
    size_t FormalParamsLengthConst(Context context, AstNode ast);
    void SetScope(Context context, AstNode ast, Scope scope);
};