/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export final class External_LITERAL_evenodd {}
export final class External_LITERAL_onzero {}
export type External_LITERAL_nonzero = string
export type External_TEMPLATE_LITERAL_number_FP = string
export type External_TEMPLATE_LITERAL_number_LPX = string
export type External_TEMPLATE_LITERAL_number_vp = string
export type External_TEMPLATE_LITERAL_number_Percentage = string
export type External_TEMPLATE_LITERAL_number_PX = string
export type External_LITERAL_identity = string
export type External_LITERAL_opacity = string
export type External_LITERAL_asymmetric = string
export type External_LITERAL_move = string
export type External_LITERAL_slideSwitch = string
export type External_LITERAL_translate = string
export type External_LITERAL_rotate = string
export type External_LITERAL_scale = string
export type External_LITERAL_high = string
export type External_LITERAL_low = string
export type External_LITERAL_medium = string
export type External_LITERAL_butt = string
export type External_LITERAL_round = string
export type External_LITERAL_square = string
export type External_LITERAL_bevel = string
export type External_LITERAL_miter = string
export type External_LITERAL_inherit = string
export type External_LITERAL_ltr = string
export type External_LITERAL_rtl = string
export type External_LITERAL_center = string
export type External_LITERAL_end = string
export type External_LITERAL_left = string
export type External_LITERAL_right = string
export type External_LITERAL_start = string
export type External_LITERAL_alphabetic = string
export type External_LITERAL_bottom = string
export type External_LITERAL_hanging = string
export type External_LITERAL_ideographic = string
export type External_LITERAL_middle = string
export type External_LITERAL_top = string
export type External_LITERAL_auto = string
export type External_LITERAL_navBar = string
export final class External_LITERAL_asyncReceiverRegister {}
export final class External_LITERAL_syncReceiverRegister {}