import { Finalizable } from "@koalaui/interop"
import { MaterializedBase } from "./MaterializedBase"
import { Serializer } from "./peers/Serializer"
import { unsafeCast } from "./shared/generated-utils"
import { runtimeType, RuntimeType, SerializerBase, registerCallback, wrapCallback } from "@koalaui/interop"
import { Deserializer, createDeserializer } from "./peers/Deserializer"
import { CallbackKind } from "./peers/CallbackKind"