package "org.openharmony.arkui";

dictionary PixelMapFormat {
    number UNKNOWN = 0;
    number RGB_565 = 2;
    number RGBA_8888 = 3;
    number BGRA_8888 = 4;
    number RGB_888 = 5;
    number ALPHA_8 = 6;
    number RGBA_F16 = 7;
    number NV21 = 8;
    number NV12 = 9;
    number RGBA_1010102 = 10;
    number YCBCR_P010 = 11;
    number YCRCB_P010 = 12;
};

dictionary AntiAliasingLevel {
    number NONE = 0;
    number LOW = 1;
    number MEDIUM = 2;
    number HIGH = 3;
};

dictionary HdrMetadataKey {
    number HDR_METADATA_TYPE = 0;
    number HDR_STATIC_METADATA = 1;
    number HDR_DYNAMIC_METADATA = 2;
    number HDR_GAINMAP_METADATA = 3;
};

dictionary HdrMetadataType {
    number NONE = 0;
    number BASE = 1;
    number GAINMAP = 2;
    number ALTERNATE = 3;
};

interface HdrStaticMetadata {
    attribute sequence<number> displayPrimariesX;
    attribute sequence<number> displayPrimariesY;
    attribute number whitePointX;
    attribute number whitePointY;
    attribute number maxLuminance;
    attribute number minLuminance;
    attribute number maxContentLightLevel;
    attribute number maxFrameAverageLightLevel;
};

[Entity=Interface]
interface GainmapChannel {
    attribute number gainmapMax;
    attribute number gainmapMin;
    attribute number gamma;
    attribute number baseOffset;
    attribute number alternateOffset;
};

interface HdrGainmapMetadata {
    attribute number writerVersion;
    attribute number miniVersion;
    attribute number gainmapChannelCount;
    attribute boolean useBaseColorFlag;
    attribute number baseHeadroom;
    attribute number alternateHeadroom;
    attribute sequence<GainmapChannel> channels;
};

typedef (HdrMetadataType or HdrStaticMetadata /*or ArrayBuffer*/ or HdrGainmapMetadata) HdrMetadataValue;

[Entity=Interface]
interface Size {
    attribute number height;
    attribute number width;
};

[Entity=Interface]
interface Region {
    attribute Size size;
    attribute number x;
    attribute number y;
};

[Entity=Interface]
interface PositionArea {
    // attribute ArrayBuffer pixels;
    attribute number offset;
    attribute number stride;
    attribute Region region;
};

dictionary AlphaType {
    number UNKNOWN = 0;
    number OPAQUE = 1;
    number PREMUL = 2;
    number UNPREMUL = 3;
};

[Entity=Interface]
interface ImageInfo {
    attribute Size size;
    attribute number density;
    attribute number stride;
    attribute PixelMapFormat pixelFormat;
    attribute AlphaType alphaType;
    attribute String mimeType;
    attribute boolean isHdr;
};

[Async, Synthetic]
callback AsyncCallback_PixelMap_Void = void (PixelMap result);
[Async, Synthetic]
callback AsyncCallback_Void = void ();
[Async, Synthetic]
callback AsyncCallback_ImageInfo_Void = void (ImageInfo result);

[/*Namespace=image,*/ Entity=Interface]
interface PixelMap {
    // (stub until issue 20764 is fixed) readonly attribute /*boolean (fix after retConverter fixed)*/ i32 isEditable;
    // (stub until issue 20764 is fixed) readonly attribute /*boolean (fix after retConverter fixed)*/ i32 isStrideAlignment;
    async void readPixelsToBuffer(buffer dst);
    void readPixelsToBuffer(buffer dst, AsyncCallback_Void callback_);
    void readPixelsToBufferSync(buffer dst);
    async void readPixels(PositionArea area);
    void readPixels(PositionArea area, AsyncCallback_Void callback_);
    void readPixelsSync(PositionArea area);
    async void writePixels(PositionArea area);
    void writePixels(PositionArea area, AsyncCallback_Void callback_);
    void writePixelsSync(PositionArea area);
    async void writeBufferToPixels(buffer src);
    void writeBufferToPixels(buffer src, AsyncCallback_Void callback_);
    void writeBufferToPixelsSync(buffer src);
    async void toSdr();
    // async ImageInfo getImageInfo();
    void getImageInfo(AsyncCallback_ImageInfo_Void callback_);
    ImageInfo getImageInfoSync();
    /*number*/ i32 getBytesNumberPerRow();
    /*number*/ i32 getPixelBytesNumber();
    /*number*/ i32 getDensity();
    void opacity(number rate, AsyncCallback_Void callback_);
    // async void opacity(number rate);
    void opacitySync(number rate);
    // async PixelMap createAlphaPixelmap();
    void createAlphaPixelmap(AsyncCallback_PixelMap_Void callback_);
    PixelMap createAlphaPixelmapSync();
    void scale(number x, number y, AsyncCallback_Void callback_);
    // async void scale(number x, number y);
    void scaleSync(number x, number y);
    // async void scale(number x, number y, AntiAliasingLevel level);
    void scaleSync(number x, number y, AntiAliasingLevel level);
    void translate(number x, number y, AsyncCallback_Void callback_);
    // async void translate(number x, number y);
    void translateSync(number x, number y);
    void rotate(number angle, AsyncCallback_Void callback_);
    // async void rotate(number angle);
    void rotateSync(number angle);
    void flip(boolean horizontal, boolean vertical, AsyncCallback_Void callback_);
    // async void flip(boolean horizontal, boolean vertical);
    void flipSync(boolean horizontal, boolean vertical);
    void crop(Region region, AsyncCallback_Void callback_);
    // async void crop(Region region);
    void cropSync(Region region);
    /*colorSpaceManager.*/ColorSpaceManager getColorSpace();
    // void marshalling(/*rpc.*/MessageSequence sequence_);
    // async PixelMap unmarshalling(/*rpc.*/MessageSequence sequence_);
    void setColorSpace(/*colorSpaceManager.*/ColorSpaceManager colorSpace);
    void applyColorSpace(/*colorSpaceManager.*/ColorSpaceManager targetColorSpace, AsyncCallback_Void callback_);
    // async void applyColorSpace(/*colorSpaceManager.*/ColorSpaceManager targetColorSpace);
    async void convertPixelFormat(PixelMapFormat targetPixelFormat);
    void release(AsyncCallback_Void callback_);
    // async void release();
    void setTransferDetached(boolean detached);
    HdrMetadataValue getMetadata(HdrMetadataKey key);
    void setMemoryNameSync(String name);
    async void setMetadata(HdrMetadataKey key, HdrMetadataValue value);
};