export enum ExtendedAttributes {
    CallSignature = "CallSignature",
    CommonMethod = "CommonMethod",
    Component = "Component",
    ComponentInterface = "ComponentInterface",
    Documentation = "Documentation",
    DtsName = "DtsName",
    Entity = "Entity",
    Import = "Import",
    IndexSignature = "IndexSignature",
    Optional = "Optional",
    Qualifier = "Qualifier",
    TypeArguments = "TypeArguments",
    TypeParameters = "TypeParameters",
    VerbatimDts = "VerbatimDts",
    Export = "Export",
    Accessor = "Accessor",
    Protected = "Protected",
    Synthetic = "Synthetic",
    Interfaces = "Interfaces",
    GlobalScope = "GlobalScope",
    Namespace = "Namespace",
}