package force_callback;
[Synthetic]
callback CallbackStringVoid = void (String value);
interface EditMenuOptions {
    attribute CallbackStringVoid onCreateMenu;
    [ExtraMethod=onCreateMenuExtraMethod]
    attribute CallbackStringVoid onCreateMenuExtraMethod_callback;
};